package io.xoboro.server.tasks

import io.xoboro.core.application.ArtworkLifecycle
import io.xoboro.core.application.DurableTask
import io.xoboro.core.application.DurableTaskQueue
import io.xoboro.core.application.TaskPriority
import io.xoboro.core.domain.ArtworkOwner
import io.xoboro.core.domain.ArtworkOwnerKind
import io.xoboro.core.domain.ArtworkRepository
import io.xoboro.core.domain.ArtworkType
import io.xoboro.core.domain.BookId
import io.xoboro.core.domain.BookRepository
import io.xoboro.core.domain.CollectionId
import io.xoboro.core.domain.ReadListId
import io.xoboro.core.domain.ReadListRepository
import io.xoboro.core.domain.SeriesCollectionRepository
import io.xoboro.core.domain.SeriesId
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

/**
 * Enqueues artwork generation for every collection and read list that has none.
 *
 * A sweep rather than a hook on each membership change: collections and read lists are mutated from
 * the native API, the compatibility API, and metadata import, and a cover derived from members is not
 * worth wiring into all three. This mirrors `FIND_BOOK_ARTWORK`, which sweeps for the same reason.
 *
 * Groups that already carry generated artwork are skipped, so re-running the sweep is cheap. A group
 * whose members changed keeps its old derived cover until the artwork is deleted - stated here
 * because it is a real limitation, not an oversight.
 */
class OrganizationArtworkTaskEmitter(
  private val collections: SeriesCollectionRepository,
  private val readLists: ReadListRepository,
  private val artwork: ArtworkRepository,
  private val queue: DurableTaskQueue,
  private val currentTimeMillis: () -> Long,
) {
  fun generateMissing(priority: Int = TaskPriority.LOWEST): Int {
    val now = currentTimeMillis()
    require(now >= 0) { "Organization artwork timestamp must not be negative" }
    val owners =
      collections.findAll().map { ArtworkOwner(ArtworkOwnerKind.COLLECTION, it.id.value) } +
        readLists.findAll().map { ArtworkOwner(ArtworkOwnerKind.READ_LIST, it.id.value) }
    return owners
      .filter { owner -> artwork.findAll(owner).none { it.type == ArtworkType.GENERATED } }
      .count { owner ->
        queue.enqueue(
          DurableTask(
            id = "${OrganizationArtworkTaskHandler.TASK_TYPE}_${owner.kind.name}_${owner.id}",
            type = OrganizationArtworkTaskHandler.TASK_TYPE,
            payloadJson =
              buildJsonObject {
                put(OrganizationArtworkTaskHandler.OWNER_KIND_FIELD, owner.kind.name)
                put(OrganizationArtworkTaskHandler.OWNER_ID_FIELD, owner.id)
              }.toString(),
            priority = priority,
            availableAtMillis = now,
          ),
          now,
        )
      }
  }
}

/**
 * Gives a collection or read list a cover derived from the first member that has one.
 *
 * This is not Komga's composite: it reuses one member's cover rather than tiling several. A single
 * borrowed cover is what closes the visible gap - a group with no cover at all - and a mosaic is a
 * visual refinement on top of it. Calling this a mosaic in the coverage doc would be the mistake.
 *
 * Members are walked in their stored order, and for a collection a series that has no artwork falls
 * through to its own first media item, because series artwork comes only from disk sidecars and is
 * frequently absent while the books underneath it all have generated covers.
 */
class OrganizationArtworkTaskHandler(
  private val collections: SeriesCollectionRepository,
  private val readLists: ReadListRepository,
  private val books: BookRepository,
  private val artwork: ArtworkRepository,
  private val lifecycle: ArtworkLifecycle,
  private val json: Json = Json,
) : TaskHandler {
  override val taskType: String = TASK_TYPE

  override fun handle(task: DurableTask) {
    require(task.type == taskType) { "Unexpected task type: ${task.type}" }
    val payload = json.parseToJsonElement(task.payloadJson).jsonObject
    val kind =
      payload[OWNER_KIND_FIELD]
        ?.jsonPrimitive
        ?.contentOrNull
        ?.let { value -> ArtworkOwnerKind.entries.firstOrNull { it.name == value } }
        ?: error("Organization artwork task must contain a known owner kind")
    val ownerId =
      payload[OWNER_ID_FIELD]
        ?.jsonPrimitive
        ?.contentOrNull
        ?.takeIf(String::isNotBlank)
        ?: error("Organization artwork task must contain an owner ID")
    val cover =
      when (kind) {
        ArtworkOwnerKind.COLLECTION -> collectionCover(CollectionId(ownerId))
        ArtworkOwnerKind.READ_LIST -> readListCover(ReadListId(ownerId))
        ArtworkOwnerKind.MEDIA_ITEM, ArtworkOwnerKind.SERIES ->
          error("Media item and series artwork is generated by GENERATE_BOOK_ARTWORK")
      } ?: return
    lifecycle.replaceGenerated(ArtworkOwner(kind, ownerId), cover)
  }

  private fun collectionCover(id: CollectionId): ByteArray? =
    collections
      .findByIdOrNull(id)
      ?.seriesIds
      ?.firstNotNullOfOrNull { seriesId ->
        selectedContent(ArtworkOwner(ArtworkOwnerKind.SERIES, seriesId.value))
          ?: firstBookCover(seriesId)
      }

  private fun readListCover(id: ReadListId): ByteArray? =
    readLists
      .findByIdOrNull(id)
      ?.bookIds
      ?.firstNotNullOfOrNull(::bookCover)

  private fun firstBookCover(seriesId: SeriesId): ByteArray? =
    books
      .findAllBySeriesId(seriesId)
      .asSequence()
      .filter { it.deletedAtMillis == null }
      .sortedWith(compareBy({ it.number }, { it.relativePath }))
      .firstNotNullOfOrNull { bookCover(it.id) }

  private fun bookCover(bookId: BookId): ByteArray? =
    selectedContent(ArtworkOwner(ArtworkOwnerKind.MEDIA_ITEM, bookId.value))

  private fun selectedContent(owner: ArtworkOwner): ByteArray? =
    artwork
      .findSelectedOrNull(owner)
      ?.let { artwork.content(owner, it.id) }
      ?.takeIf { it.isNotEmpty() }

  companion object {
    const val TASK_TYPE = "GENERATE_ORGANIZATION_ARTWORK"
    internal const val OWNER_KIND_FIELD = "ownerKind"
    internal const val OWNER_ID_FIELD = "ownerId"
  }
}
